### ISSUE TITLE
2.8.1 has no changelog entry

### ISSUE THREAD

**Issue by andreasabel** [BNFC/bnfc#191]
2.8.1 has no changelog entry on hackage, see https://hackage.haskell.org/package/BNFC-2.8.1/changelog

**Comment by gdetrez** [comment]
Indeed. That's embarassing :confused: 

I added the entry for 2.8.1 in the changelog in master and a summary of the changes since then. I think it will be easier to create the changelog progressively than trying to write it when releasing. (or forgetting to do so...)

I'm not sure I can do anything on hackage on the other hand. If I understood correctly, you can't change a release once it's been uploaded.
