### ISSUE TITLE
Use Stack to build bnfc

### ISSUE THREAD

**Issue by pascalh** [BNFC/bnfc#198]
Recently [stack](https://haskellstack.org/) gets more and more popular, since it avoids cabal-hell, eases updating used packages and ghc and also uses a sandbox for every project by default. Stack also allows the ease use of different versions of ghc on a system. Hereby I suggest to use stack as a build tool for bnfc.

**Comment by metaleap** [comment]
Did this PR get accepted? If not, and anyone comes across this: one can, in the `sources` sub-directory, do a `stack init` (creates a stack.yaml from the .cabal file) then `stack install`, this worked at my end. Only oddity is that using the current git repo you get 2.8 whereas if you don't clone at all, ever and just do `stack install BNFC` *outright* instead, you already get 2.8.1 😏

**Comment by pascalh** [comment]
@metaleap waiting for an answer regarding this PR. This is exactly what I did to raise this PR ;)

Master is the dev branch and you find the branch for 2.8.1 [here](https://github.com/BNFC/bnfc/tree/2.8.x). However, the version number in master should be bumped to 2.8.1 as well.

**Comment by ip1981** [comment]
First of all you can use Stack as is. If you find yourself in need of many files and configuration for Stack you are in Stack-hell.

Second, cabal-hell is no longer a problem since we have new builds with http://cabal.readthedocs.io/en/latest/nix-local-build-overview.html

And `cabal new-freeze` is a way better than Stack's snapshots, because information is local. But both mean flaws in design and Haskell code quality. Good old `.cabal` file ought to be enough with minimal version requirements and packages must maintain backward compatibility.

P. S. Yes, I dislike Stack.

**Comment by rabbitonweb** [comment]
@ip1981 so.... instead of helping with the issue, you've decided to spent this time to tell us how you don't like Stack.. well, that was soooooo helpful! Thank you! It moved this issue forward.

P.S Yes, irony
P.P.S Being ridiculous is ridiculous

**Comment by andreasabel** [comment]
#199 has been merged, I suppose this issue can be closed.

**Comment by andreasabel** [comment]
See #241: BNFC is now on stackage.
