### ISSUE TITLE
Add javascript backend usin Jison

### ISSUE THREAD

**Issue by gdetrez** [BNFC/bnfc#2]
Jison is a port of flex/yacc in javascript so it might not be so hard to derive a javascript backend from the C one

**Comment by maxnordlund** [comment]
This would be awesome. I like the idea to define the grammar for a language once, and then compile it into concrete parsers in various languages. But more importantly not having any embedded code in the grammar files, and allow automatic AST node types generation.

Then be able to do the same in the browser is just mind boggling. This would allow an syntax highlighter/editor to stay compatible with the language. No more divergence because the consumer was written in another language. Anyway, I really like what you have been doing. Thanks for all the hard work.

**Comment by gdetrez** [comment]
Thanks. Note that there have been some work going in the direction of highlighter with the new [pygments generator](http://bnfc.readthedocs.org/en/latest/user_guide.html#pygments) if you're interested.
