### ISSUE TITLE
Using terminals defined in a rule in other rules

### ISSUE THREAD

**Issue by tymm** [BNFC/bnfc#207]
```
EKeyword.           Exp ::= "keyword" Exp2 ;
EDef.               Exp ::= "def" Exp2 Exp2 ;
EIdent.             Exp2 ::= Ident ;

terminator Exp "" ;
coercions Exp 2 ;
```
I want to be able to both parse the strings `def keyword id` and `keyword id` to their respective abstract syntax as defined in the LBNF above.
Parsing `keyword id` works fine. However parsing `def keyword id` does not work.

I'm not sure if this is a feature or a bug. If it is a feature, any help on how to do it right is highly appreciated.

**Comment by pascalh** [comment]
The grammar definition looks a bit strange, because I don't see the need for `coercions` here. If you really only want to parse strings like `def keyword id` and `keyword id`, this is the grammar you are looking for:

```
EKeyword.           Exp ::= "keyword" Id ;
EDef.               Exp ::= "def" "keyword" Id ;
EIdent.             Id ::= Ident ;
```
You could even simplify it to:

```
EKeyword.           Exp ::= "keyword" Ident ;
EDef.               Exp ::= "def" "keyword" Ident ;
```
in case you don't need the wrapper.

If I understood your use case wrong, feel free to ask again.

**Comment by tymm** [comment]
Sorry, you are completely right. I tried to simplify my actual problem too much.
```
ECond.                Exp ::= "(" "cond" "(" Id ")" ")" ;
EDef.                 Exp ::= "(" "def" "(" Id Id ")" ")" ;
EIdent.               Id ::= Ident ;
```
Here we have the situation that `(def (cond foo))` is not being parsed even though it should be parsed to `EDef`, right?.
I have all those single `"("` and `")"` because I want to allow for whitespace between tokens.

**Comment by pascalh** [comment]
The string `(def (cond foo))` is not being parsed successfully, because `cond` is a symbol (due to rule `ECond`). Symbols (also called reserved words or keywords) are treated differently than regular identifiers. Hence, the string `(def (con foo))` is being parsed while `(def (cond foo))` is being rejected.

Handling multiple whitespaces between tokens is enabled by default.

**Comment by tymm** [comment]
Thanks a lot for your answer.

Is there a way to make `cond` not become a symbol?

**Comment by pascalh** [comment]
As soon as you use a string constant in your grammar it becomes a symbol. There is no way of avoiding this as far as I know.

**Comment by tymm** [comment]
Thanks a lot for explaining!

**Comment by TheMaverickProgrammer** [comment]
This ought to be a part of the docs. I struggled with this problem having defined some "built in" variables only to find out they were clashing with `Ident` rules as described.
