### ISSUE TITLE
Release BNFC-2.8.2

### ISSUE THREAD

**Issue by andreasabel** [BNFC/bnfc#234]
TODO checklist before release:

- [x] Update changelog if necessary.
- [x] Test on latest GHCs.
- [ ] Maybe fix #233.
- [x] Update copyright note to include recent collaborators.
- [ ] Credits for version 2.8.2: "This version was brought to you by..."

Anything else?

**Comment by AndreasLoow** [comment]
The `source/changelog` changelog seems to include most things done since the last release, there are probably a few things missing but I think the changelog is probably good enough as is. (I deleted another stale changelog.) (Everything on the BNFC website (bnfc.digitalgrammars.com) seem out of date, there's e.g. no mention of any 2.8.* release.)

Based on the docs for the newly released GHC 8.6, OverlappingInstances is still there (so #233 could be postponed further). I have however not tried to build master with GHC 8.6 as it's not available through brew yet. I don't think 8.6 is available on Travis yet either, but I'm not sure. 

As for updating copyright notices, I think it's enough to just add the current maintainer, i.e. you. (I've done this.)
